/**
 * AES-256-GCM channel encryption for SecureComm.
 *
 * Each channel (global chat + every group) has its own 256-bit AES key
 * generated by the server.  Keys are distributed over the WSS connection
 * (already protected by TLS) and imported here as non-exportable CryptoKeys.
 *
 * Messages are prefixed with "enc:" so old plaintext messages still render.
 */

// channelId → CryptoKey  (populated on login via loadChannelKeys)
export const channelKeys = new Map();

/**
 * Import a map of { channelId: base64Key } into channelKeys.
 * Called when the server sends keys in welcome / group_history.
 */
export async function loadChannelKeys(keyMap) {
  if (!keyMap) return;
  for (const [channelId, b64] of Object.entries(keyMap)) {
    try {
      const raw = Uint8Array.from(atob(b64), c => c.charCodeAt(0));
      const key = await crypto.subtle.importKey(
        'raw', raw,
        { name: 'AES-GCM', length: 256 },
        false,                      // non-exportable
        ['encrypt', 'decrypt']
      );
      channelKeys.set(channelId, key);
    } catch (e) {
      console.error('[crypto] failed to import key for', channelId, e);
    }
  }
}

/**
 * Encrypt a plaintext string for the given channel.
 * Returns  "enc:<base64(IV + ciphertext)>"
 */
export async function encryptMsg(channelId, plaintext) {
  const key = channelKeys.get(channelId);
  if (!key) return plaintext; // no key yet — send as-is (shouldn't happen post-login)

  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = await crypto.subtle.encrypt(
    { name: 'AES-GCM', iv },
    key,
    new TextEncoder().encode(plaintext)
  );

  const out = new Uint8Array(12 + ct.byteLength);
  out.set(iv, 0);
  out.set(new Uint8Array(ct), 12);
  return 'enc:' + btoa(String.fromCharCode(...out));
}

/**
 * Decrypt an "enc:..." message for the given channel.
 * Passes through plaintext messages (no "enc:" prefix) unchanged — backwards compat.
 */
export async function decryptMsg(channelId, text) {
  if (!text || !text.startsWith('enc:')) return text;

  const key = channelKeys.get(channelId);
  if (!key) return '[encrypted]';

  try {
    const data = Uint8Array.from(atob(text.slice(4)), c => c.charCodeAt(0));
    const plain = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: data.slice(0, 12) },
      key,
      data.slice(12)
    );
    return new TextDecoder().decode(plain);
  } catch {
    return '[encrypted message]';
  }
}

/** Decrypt an array of message objects for a given channel. */
export async function decryptHistory(messages, channelId) {
  return Promise.all(
    (messages || []).map(async m => ({
      ...m,
      text: await decryptMsg(channelId, m.text),
    }))
  );
}
